# Generated by Django 6.0.4 on 2026-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=100)),
                ('available_places', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_waiting_list_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_first_name', models.CharField(max_length=100)),
                ('parent_last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('child_age', models.CharField(max_length=50)),
                ('desired_date', models.DateField()),
                ('hours_per_week', models.PositiveIntegerField()),
                ('requested_days', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('rgpd_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('meal_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('caf_info', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
